#!/usr/bin/env bash

THISDIR="$( cd "$(dirname "$( readlink -f ${BASH_SOURCE[0]} )")" >/dev/null 2>&1 && pwd)"
# echo "THISDIR $THISDIR"

source "$THISDIR/commands.sh"

CMD=$1

if [[ -z "$CMD" ]]; then
    echo "You must specify a command"
elif [[ "$CMD" == "nginx" ]]; then
    InstallNginx
elif [[ "$CMD" == "service" ]]; then
    InstallService
else
    echo "Invalid command"
fi
