#!/bin/bash

THISDIR="$( cd "$(dirname "$( readlink -f ${BASH_SOURCE[0]} )")" >/dev/null 2>&1 && pwd)"
# echo "THISDIR $THISDIR"

source "$THISDIR/commands.bash"

CMD=$1

if [[ -z "$CMD" ]]; then
    echo "You must specify a command"
elif [[ "$CMD" == "nginx" ]]; then
    UninstallNginx
elif [[ "$CMD" == "service" ]]; then
    UinstallService
else
    echo "Invalid command"
fi
